### ISSUE TITLE
Java build with Hadoop 2.5.1, 2.5.2 test failed (passed with 0.2x, 1.0.4 and 1.1.2)

### ISSUE THREAD

**Issue by chanwit** [quantcast/qfs#47]
I am eager to help fixing this, if any one can shed some lights.
(It's my first time hacking QFS.)

Here's the stack trace of the test:
-------------------------------------------------------------------------------
Test set: com.quantcast.qfs.hadoop.TestQuantcastFileSystem
-------------------------------------------------------------------------------
Tests run: 4, Failures: 1, Errors: 2, Skipped: 0, Time elapsed: 1.482 sec <<< FAILURE!
testFiles(com.quantcast.qfs.hadoop.TestQuantcastFileSystem)  Time elapsed: 1.435 sec  <<< ERROR!
java.lang.NullPointerException
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1010)
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:482)
	at org.apache.hadoop.util.Shell.run(Shell.java:455)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:702)
	at org.apache.hadoop.util.Shell.execCommand(Shell.java:791)
	at org.apache.hadoop.util.Shell.execCommand(Shell.java:774)
	at org.apache.hadoop.fs.RawLocalFileSystem.setPermission(RawLocalFileSystem.java:646)
	at org.apache.hadoop.fs.FilterFileSystem.setPermission(FilterFileSystem.java:472)
	at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:460)
	at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:426)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:906)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:887)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:784)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:773)
	at com.quantcast.qfs.hadoop.QFSEmulationImpl.create(QFSEmulationImpl.java:208)
	at com.quantcast.qfs.hadoop.QuantcastFileSystem.create(QuantcastFileSystem.java:167)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:906)
	at com.quantcast.qfs.hadoop.TestQuantcastFileSystem.testFiles(TestQuantcastFileSystem.java:101)

testFileIO(com.quantcast.qfs.hadoop.TestQuantcastFileSystem)  Time elapsed: 0.015 sec  <<< ERROR!
java.lang.NullPointerException
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1010)
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:482)
	at org.apache.hadoop.util.Shell.run(Shell.java:455)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:702)
	at org.apache.hadoop.util.Shell.execCommand(Shell.java:791)
	at org.apache.hadoop.util.Shell.execCommand(Shell.java:774)
	at org.apache.hadoop.fs.RawLocalFileSystem.setPermission(RawLocalFileSystem.java:646)
	at org.apache.hadoop.fs.FilterFileSystem.setPermission(FilterFileSystem.java:472)
	at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:460)
	at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:426)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:906)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:887)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:784)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:773)
	at com.quantcast.qfs.hadoop.QFSEmulationImpl.create(QFSEmulationImpl.java:208)
	at com.quantcast.qfs.hadoop.QuantcastFileSystem.create(QuantcastFileSystem.java:167)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:906)
	at com.quantcast.qfs.hadoop.TestQuantcastFileSystem.testFileIO(TestQuantcastFileSystem.java:136)

testDirs(com.quantcast.qfs.hadoop.TestQuantcastFileSystem)  Time elapsed: 0 sec  <<< FAILURE!
junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at junit.framework.Assert.assertFalse(Assert.java:34)
	at junit.framework.Assert.assertFalse(Assert.java:41)
	at com.quantcast.qfs.hadoop.TestQuantcastFileSystem.testDirs(TestQuantcastFileSystem.java:85)

**Comment by fsareshwala** [comment]
Hi Chanwit, it's been a while since you posted in this thread. Do you still need help? I assume that you got things working. If not, please feel free to open another issue. I'm closing this one out for now.

**Comment by chanwit** [comment]
Thank @fsareshwala I don't think it matters at the moment. Will be open another one if I encounter something.
