### ISSUE TITLE
Failed to initialize YarnClient (Hadoop 2.6.0 and QFS 1.1.2)

### ISSUE THREAD

**Issue by zixuanhe** [quantcast/qfs#56]
The error message below was returned when running hadoop example test following instructions on http://www.abisen.com/configuring-qfs-on-cloudera-hadoop.html

Both qfsshell and hdfs commands are functional, such that the qfs cluster should have been setup properly. 

It seems someone has encountered similar issue as well, https://groups.google.com/forum/#!topic/qfs-devel/D3HAoatGAG4

Command to run the hadoop test: 
```
bin/hadoop jar $HADOOP_PREFIX/share/hadoop/mapreduce/hadoop-mapreduce-examples-2.6.0.jar grep  $QFSPARAM /input/hadoop /output 'dfs[a-z.]+'
```

```
echo $QFSPARAM
-Dfs.qfs.impl=com.quantcast.qfs.hadoop.QuantcastFileSystem -Dfs.defaultFS=qfs://172.17.1.249:20000 -Dfs.qfs.metaServerHost=172.17.1.249 -Dfs.qfs.metaServerPort=20000 -libjars /lib/java/hadoop-qfs/hadoop-2.6.0-qfs-1.1.2.jar 
```

```
$ cat mapred-site.xml
<configuration>
    <property>
        <name>mapreduce.framework.name</name>
        <value>yarn</value>
    </property>
</configuration>
```

15/02/18 00:56:25 INFO mapreduce.Cluster: Failed to use org.apache.hadoop.mapred.YarnClientProtocolProvider due to error: Error in instantiating YarnClient
java.io.IOException: Cannot initialize Cluster. Please check your configuration for mapreduce.framework.name and the correspond server addresses.
	at org.apache.hadoop.mapreduce.Cluster.initialize(Cluster.java:120)
	at org.apache.hadoop.mapreduce.Cluster.<init>(Cluster.java:82)
	at org.apache.hadoop.mapreduce.Cluster.<init>(Cluster.java:75)
	at org.apache.hadoop.mapreduce.Job$9.run(Job.java:1266)
	at org.apache.hadoop.mapreduce.Job$9.run(Job.java:1262)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
	at org.apache.hadoop.mapreduce.Job.connect(Job.java:1261)
	at org.apache.hadoop.mapreduce.Job.submit(Job.java:1290)
	at org.apache.hadoop.mapreduce.Job.waitForCompletion(Job.java:1314)
	at org.apache.hadoop.examples.Grep.run(Grep.java:77)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.examples.Grep.main(Grep.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.util.ProgramDriver$ProgramDescription.invoke(ProgramDriver.java:71)
	at org.apache.hadoop.util.ProgramDriver.run(ProgramDriver.java:144)
	at org.apache.hadoop.examples.ExampleDriver.main(ExampleDriver.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)

**Comment by kstinsonqc** [comment]
Can you post the core-site.xml and yarn-site.xml files that you are using too?

**Comment by zixuanhe** [comment]
FYI, @kstinsonqc 

Same yarn-site.xml and mapped-site.xml have been used with HDFS and Hadoop without problem. 

```
$ cat core-site.xml
<configuration>
    <property>
        <name>fs.defaultFS</name>
        <value>qfs://172.17.1.249:20000</value>
    </property>
    <property>
        <name>io.file.buffer.size</name>
        <value>131072</value>
    </property>
</configuration>
```

```
$ cat yarn-site.xml
<configuration>
    <property>
        <name>yarn.nodemanager.aux-services</name>
        <value>mapreduce_shuffle</value>
    </property>
    <property>
        <name>yarn.resourcemanager.address</name>
        <value>172.17.1.249:8032</value>
    </property>
    <property>
        <name>yarn.resourcemanager.resource-tracker.address</name>
        <value>172.17.1.249:8031</value>
    </property>
    <property>
        <name>yarn.resourcemanager.scheduler.address</name>
        <value>172.17.1.249:8030</value>
    </property>
</configuration>

```

**Comment by kstinsonqc** [comment]
The properties needed to use the qfs:// uri may not be propagating to all the java processes that need them.

Try adding
````
   <property>
        <name>fs.AbstractFileSystem.qfs.impl</name>
        <value>com.quantcast.qfs.hadoop.Qfs</value>
    </property>
   <property>
        <name>fs.qfs.impl</name>
        <value>com.quantcast.qfs.hadoop.QuantcastFileSystem</value>
    </property>
````
to your core-site.xml

**Comment by zixuanhe** [comment]
Thank you so much. The issue is fixed by adding the suggested properties in core-site.xml. 

However, when I was trying the run the hadoop example applications, the task container reported that it failed to initialize KFS client. Details are reported in #57

**Comment by fsareshwala** [comment]
Hi there,

This issue is now being tracked on the QFS JIRA instance. The reference ticket is: https://quantcast.atlassian.net/browse/QFS-56
