### ISSUE TITLE
C client library is not "fork safe"

### ISSUE THREAD

**Issue by ygrek** [quantcast/qfs#64]
E.g. in our use-case parent process forks workers and waits for them to finish, once workers exit, parent process hangs at exit in
```
#0  __pthread_cond_destroy (cond=0x4bde7c0) at pthread_cond_destroy.c:77
#1  0x00007f2976fb7b79 in QCCondVar::~QCCondVar() () from /usr/lib/libqfs_qcdio.so
#2  0x00007f2976aa0bfd in KFS::BufferedLogWriter::~BufferedLogWriter() () from /usr/lib/libqfs_common.so
#3  0x00007f29758e7bc9 in __run_exit_handlers (status=0, listp=0x7f2975c535a8 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true) at exit.c:82
#4  0x00007f29758e7c15 in __GI_exit (status=<optimized out>) at exit.c:104
```

**Comment by fsareshwala** [comment]
Hi there,

This issue is now being tracked on the QFS JIRA instance. The reference ticket is: https://quantcast.atlassian.net/browse/QFS-64
